Sprint 6. To review
yaengine/java-kanban pull request #1
Opened 2024-11-27 21:34 UTC by yaengine

2024-11-28 20:23 UTC, Fleaman777 requested changes

2024-11-28 20:23 UTC, Fleaman777 commented on src/manager/Node.java
> +public class Node<T> {
по сути, Node класс не имеет особого смысла без логики, которая реализована в InMemoryHistoryManager, поэтому его можно было бы сделать внутренним классом в InMemoryHistoryManager.

2024-11-28 20:23 UTC, Fleaman777 commented on src/manager/InMemoryTaskManager.java
не хватает использование метода remove истории, а методах с полным удалением задач

2024-11-28 20:23 UTC, Fleaman777 commented on test/manager/InMemoryTaskManagerTest.java
> +    }
более правильный подход, когда у теста только 1 assert. А у тебя получается, что ты тестируешь разные кейсы в одном методе, что не очень хорошо для поддержки и восприятия тестов

2024-11-28 21:59 UTC, yaengine commented on src/manager/Node.java
> +public class Node<T> {
Принято, исправил.

2024-11-28 21:59 UTC, yaengine commented on src/manager/InMemoryTaskManager.java
Принято. Добавил.

2024-11-28 22:04 UTC, yaengine commented on test/manager/InMemoryTaskManagerTest.java
> +    }
Принято.
Тема холиварная, в качестве аргумента
https://stackoverflow.blog/2022/11/03/multiple-assertions-per-test-are-fine/
https://softwareengineering.stackexchange.com/questions/7823/is-it-ok-to-have-multiple-asserts-in-a-single-unit-test

Но согласен, что надо руководствоваться здравым смыслом и не проверять разные кейсы в одном тесте.
Порефаторил тесты, конкретно в этом кейсе оставил эти две проверки вместе, т.к. проверяю удаление и эпика и его подзадачи.

2024-11-29 19:43 UTC, Fleaman777 commented on test/manager/InMemoryTaskManagerTest.java
> +    }
засчитано, 

и отличный сделал вывод,

2024-11-29 19:43 UTC, Fleaman777 approved these changes

2024-12-09 20:39 UTC, merged