Sprint 7. To review
yaengine/java-kanban pull request #2
Opened 2024-12-12 21:45 UTC by yaengine

2024-12-13 21:34 UTC, Fleaman777 requested changes

2024-12-13 21:34 UTC, Fleaman777 commented on src/manager/FileBackedTaskManager.java
> +    public static InMemoryTaskManager loadFromFile(File file) {
у этого метода, согласно тз. жолжен быть другой возвр тип

2024-12-13 21:34 UTC, Fleaman777 commented on src/manager/FileBackedTaskManager.java
> +    private static Task fromString(String value) {
этот метод не должен быть static

2024-12-13 21:34 UTC, Fleaman777 commented on src/manager/FileBackedTaskManager.java
> +            retTask = new Task(values[2], values[4], TaskStatus.valueOf(values[3]), Integer.parseInt(values[0]));
для того, что бы в значениях из массива можно было легче ориентироваться, хорошо было бы их вынести в локальные переменные с подходящими названиями

2024-12-13 21:34 UTC, Fleaman777 commented on src/manager/FileBackedTaskManager.java
> +    static class ManagerSaveException extends RuntimeException {
принято эксепшен классы выносить в отдельный файл, 
к томе же этот эксепшен может использоваться в др местах

2024-12-13 21:34 UTC, Fleaman777 commented on test/manager/FileBackedTaskManagerTest.java
> +}
хорошие тесты, покрывают много кейсов,
но проверь по тз езе раз, все ли протестировано

2024-12-14 22:10 UTC, yaengine commented on src/manager/FileBackedTaskManager.java
> +    public static InMemoryTaskManager loadFromFile(File file) {
Верно, исправил

2024-12-14 22:10 UTC, yaengine commented on src/manager/FileBackedTaskManager.java
> +    private static Task fromString(String value) {
Принято, исправил

2024-12-14 22:10 UTC, yaengine commented on src/manager/FileBackedTaskManager.java
> +            retTask = new Task(values[2], values[4], TaskStatus.valueOf(values[3]), Integer.parseInt(values[0]));
Принято, исправил

2024-12-14 22:10 UTC, yaengine commented on src/manager/FileBackedTaskManager.java
> +    static class ManagerSaveException extends RuntimeException {
Принято, вынес

2024-12-14 22:11 UTC, yaengine commented on test/manager/FileBackedTaskManagerTest.java
> +}
Принято, добавил

2024-12-16 08:41 UTC, Fleaman777 approved these changes

2024-12-23 22:06 UTC, merged